
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pphkyhrdfcceeuwgeqgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwaGt5aHJkZmNjZWV1d2dlcWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NTA2NTUsImV4cCI6MjA1NDMyNjY1NX0.RGfDegWptQst27i3RRcFQTagjmvA3vm9XCo8jG9Wn6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  }
});
